import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { ReactNode } from "react";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<body className="antialiased">
				<header className="border-b">
					<nav className="mx-auto max-w-6xl px-4 py-3 flex items-center justify-between">
						<Link href="/" className="font-semibold">Choreo</Link>
						<div className="flex gap-4 text-sm">
							<Link href="/choreographers">Choreographers</Link>
							<Link href="/bookings">Bookings</Link>
							<Link href="/api/auth/signin">Sign in</Link>
						</div>
					</nav>
				</header>
				<main className="mx-auto max-w-6xl px-4 py-8">
					{children}
				</main>
			</body>
		</html>
	);
}
